version: "3.8"

networks:
  my-network:
    name: my-network
    driver: bridge

services:
  backend:
    build: ./backend
    container_name: backend-container
    env_file:
      - .env
    networks:
      - "my-network"
    ports:
      - "3000:3000"
    depends_on:
      - ${HOST}
    volumes:
      - ./backend/src:/app/backend/src
    environment:
      - DB=${DB}
      - USER=${USER}
      - HOST=${HOST}
      - PASSWORD=${PASSWORD}

  database:
    image: mysql:5.7
    container_name: database-container
    env_file:
      - .env
    networks:
      - "my-network"
    volumes:
      - ./backend/database/config:/etc/mysql
      - ./backend/database/data:/var/lib/mysql
      - ./backend/database/backup:/data_backup/data
    environment:
      - MYSQL_USER=${USER}
      - MYSQL_DATABASE=${DB}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
