version: "3.8"

networks:
  my-network:
    name: my-network
    driver: bridge

services:
  database:
    image: mysql:5.7
    container_name: database-container
    env_file:
      - .env
    networks:
      - "my-network"
    volumes:
      - ./backend/database/config:/etc/mysql
      - ~/backend/database/data:/var/lib/mysql
      - ./backend/database/backup:/data_backup/data
    environment:
      - MYSQL_USER=${USER}
      - MYSQL_DATABASE=${DB}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
  backend:
    build: ./backend
    container_name: backend-container
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - "my-network"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend/src:/app/backend/src
 
    environment:
      - DB=${DB}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - BACKEND_PORT=${BACKEND_PORT}
  frontend:
    build: ./frontend
    container_name: frontend-container
    env_file:
      - .env
    links: 
      - backend
    depends_on: 
      - backend
    networks: 
      - "my-network"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
    # need chokidar in windows to hot reload
    environment:
      - CHOKIDAR_USEPOLLING=true





